server:
  ip: localhost
  port: 8000

spring:
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 1000

zookeeper:
  connect-string: localhost:2181
  session-timeout: 30000
  connection-timeout: 15000

metaServer:
  role: metaServer1
  replicaNumber: 3
